#!/usr/bin/env python3
"""
Click2Call International Rates Table Builder
=============================================
Usage:
    python3 build-rates-table.py

This script reads the latest CSV from assets/rates/ (the most recently
modified .csv file in that folder) and regenerates the international rates
table section inside pricing.html.

To update the rates in future:
  1. Drop the new CSV file into assets/rates/
  2. Run:  python3 build-rates-table.py
  3. Commit and push pricing.html to GitHub.

The script replaces everything between these two HTML comment markers:
    <!-- RATES_TABLE_START -->
    <!-- RATES_TABLE_END -->

Do NOT remove or rename those markers in pricing.html.
"""

import csv
import os
import glob
import re
from datetime import datetime

# ── Config ────────────────────────────────────────────────────────────────────
RATES_DIR = os.path.join(os.path.dirname(__file__), "assets", "rates")
PRICING_HTML = os.path.join(os.path.dirname(__file__), "pricing.html")
START_MARKER = "<!-- RATES_TABLE_START -->"
END_MARKER = "<!-- RATES_TABLE_END -->"

# ── Find latest CSV ───────────────────────────────────────────────────────────
csv_files = glob.glob(os.path.join(RATES_DIR, "*.csv"))
if not csv_files:
    raise FileNotFoundError(f"No CSV files found in {RATES_DIR}")
latest_csv = max(csv_files, key=os.path.getmtime)
csv_filename = os.path.basename(latest_csv)
print(f"Using rates file: {csv_filename}")

# ── Parse CSV ─────────────────────────────────────────────────────────────────
rows = []
current_country = ""
with open(latest_csv, newline="", encoding="utf-8-sig") as f:
    reader = csv.reader(f)
    next(reader)  # skip header row
    for row in reader:
        if not row or len(row) < 2:
            continue
        country = row[0].strip() if row[0].strip() else current_country
        if row[0].strip():
            current_country = country
        call_type = row[1].strip() if len(row) > 1 else ""
        flagfall = row[2].strip() if len(row) > 2 else ""
        rate = row[3].strip() if len(row) > 3 else ""

        # Skip completely empty rows
        if not call_type:
            continue

        is_disabled = "Route Disabled" in call_type
        # Clean up call type label
        display_type = re.sub(r"\*\s*", "", call_type).replace(" (Route Disabled)", "").strip()

        rows.append({
            "country": country,
            "call_type": display_type,
            "flagfall": flagfall,
            "rate": rate,
            "disabled": is_disabled,
        })

# ── Build HTML ────────────────────────────────────────────────────────────────
active_count = sum(1 for r in rows if not r["disabled"])
updated_date = datetime.now().strftime("%-d %B %Y")

table_rows_html = []
for r in rows:
    if r["disabled"]:
        row_class = "rates-row disabled-row hidden"
        rate_cell = '<span class="text-gray-400 text-xs italic">Not available</span>'
        flagfall_cell = '<span class="text-gray-400">—</span>'
    else:
        row_class = "rates-row"
        rate_val = r["rate"] if r["rate"] else "—"
        rate_cell = f'<span class="font-mono text-gray-900">{rate_val}</span>'
        flagfall_val = r["flagfall"] if r["flagfall"] else "—"
        flagfall_cell = f'<span class="font-mono text-gray-600">{flagfall_val}</span>'

    country_lower = r["country"].lower()
    type_lower = r["call_type"].lower()

    table_rows_html.append(
        f'      <tr class="{row_class}" data-country="{country_lower}" data-type="{type_lower}">\n'
        f'        <td class="px-4 py-2 text-gray-800 font-medium whitespace-nowrap">{r["country"]}</td>\n'
        f'        <td class="px-4 py-2 text-gray-600">{r["call_type"]}</td>\n'
        f'        <td class="px-4 py-2 text-center">{flagfall_cell}</td>\n'
        f'        <td class="px-4 py-2 text-center">{rate_cell}</td>\n'
        f'      </tr>'
    )

table_rows_str = "\n".join(table_rows_html)

html_block = f"""{START_MARKER}
        <!-- INTERNATIONAL RATES TABLE — auto-generated by build-rates-table.py on {updated_date} -->
        <!-- Source file: {csv_filename} | Active routes: {active_count} -->
        <div class="py-16 bg-gray-50 rounded-2xl my-8 border border-gray-100" id="international-rates">
          <div class="max-w-5xl mx-auto px-4 sm:px-6 lg:px-8">
            <h2 class="text-3xl font-extrabold text-center text-brand-charcoal sm:text-4xl">International Call Rates</h2>
            <p class="text-center mt-4 text-lg text-gray-500 max-w-2xl mx-auto">All rates are per minute, ex GST, and are deducted from your prepaid account balance. Rates effective {updated_date}.</p>

            <!-- Search + toggle -->
            <div class="mt-8 flex flex-col sm:flex-row gap-3 items-center justify-between">
              <div class="relative w-full sm:max-w-sm">
                <svg class="absolute left-3 top-1/2 -translate-y-1/2 w-4 h-4 text-gray-400" fill="none" stroke="currentColor" viewBox="0 0 24 24" aria-hidden="true"><path stroke-linecap="round" stroke-linejoin="round" stroke-width="2" d="M21 21l-4.35-4.35M17 11A6 6 0 1 0 5 11a6 6 0 0 0 12 0z"/></svg>
                <input id="rates-search" type="search" placeholder="Search country or call type..." class="w-full pl-9 pr-4 py-2 border border-gray-300 rounded-lg text-sm focus:outline-none focus:ring-2 focus:ring-brand-green" aria-label="Search international rates" />
              </div>
              <label class="flex items-center gap-2 text-sm text-gray-600 cursor-pointer select-none">
                <input id="rates-show-disabled" type="checkbox" class="rounded border-gray-300 text-brand-green focus:ring-brand-green" />
                Show unavailable routes
              </label>
            </div>

            <!-- No results message -->
            <p id="rates-no-results" class="hidden text-center text-gray-500 mt-6 text-sm">No matching countries or call types found.</p>

            <!-- Table -->
            <div class="mt-6 overflow-x-auto rounded-xl border border-gray-200 shadow-sm">
              <table class="min-w-full text-sm divide-y divide-gray-200" id="rates-table">
                <thead class="bg-gray-100 text-xs uppercase tracking-wide text-gray-500">
                  <tr>
                    <th class="px-4 py-3 text-left">Country / Region</th>
                    <th class="px-4 py-3 text-left">Call Type</th>
                    <th class="px-4 py-3 text-center">Flagfall (ex GST)</th>
                    <th class="px-4 py-3 text-center">Rate per min (ex GST)</th>
                  </tr>
                </thead>
                <tbody class="bg-white divide-y divide-gray-100">
{table_rows_str}
                </tbody>
              </table>
            </div>

            <p class="text-xs text-gray-400 mt-4 text-center">Rates are subject to change. Last updated: {updated_date}. Source: {csv_filename}.</p>
          </div>
        </div>

        <!-- Rates table live-filter script -->
        <script>
        (function() {{
          var searchInput = document.getElementById('rates-search');
          var showDisabled = document.getElementById('rates-show-disabled');
          var noResults = document.getElementById('rates-no-results');
          var rows = document.querySelectorAll('#rates-table tbody tr.rates-row');

          function filterRates() {{
            var query = searchInput.value.toLowerCase().trim();
            var includeDisabled = showDisabled.checked;
            var visible = 0;
            rows.forEach(function(row) {{
              var isDisabled = row.classList.contains('disabled-row');
              if (isDisabled && !includeDisabled) {{
                row.classList.add('hidden');
                return;
              }}
              var country = row.dataset.country || '';
              var type = row.dataset.type || '';
              var match = !query || country.includes(query) || type.includes(query);
              if (match) {{
                row.classList.remove('hidden');
                visible++;
              }} else {{
                row.classList.add('hidden');
              }}
            }});
            noResults.classList.toggle('hidden', visible > 0);
          }}

          searchInput.addEventListener('input', filterRates);
          showDisabled.addEventListener('change', filterRates);
          // Run once on load to hide disabled rows by default
          filterRates();
        }})();
        </script>
{END_MARKER}"""

# ── Inject into pricing.html ──────────────────────────────────────────────────
with open(PRICING_HTML, "r", encoding="utf-8") as f:
    content = f.read()

if START_MARKER not in content:
    raise ValueError(
        f"Could not find '{START_MARKER}' in pricing.html.\n"
        "Please ensure the marker exists in the file before running this script."
    )

# Replace everything between (and including) the markers
pattern = re.compile(
    re.escape(START_MARKER) + r".*?" + re.escape(END_MARKER),
    re.DOTALL,
)
new_content = pattern.sub(html_block, content)

with open(PRICING_HTML, "w", encoding="utf-8") as f:
    f.write(new_content)

print(f"Done. Injected {active_count} active routes into pricing.html.")
print(f"To update rates in future: drop a new CSV into assets/rates/ and re-run this script.")
