import json

faq_data = {
    "Adelaide": [
        {"q": "Can I get an Adelaide 08 phone number with VoIP?", "a": "Yes, Click2Call offers local Adelaide 08 phone numbers that operate over VoIP. You can either obtain a new 08 number or port your existing one seamlessly, ensuring no downtime during the transfer. This service allows you to maintain a local South Australian presence while benefiting from VoIP technology."},
        {"q": "Do I need a technician to set up a VoIP system in Adelaide?", "a": "No, you do not need a technician to set up a VoIP system in Adelaide. Click2Call offers a self-serve setup where you sign up online, select your number, configure settings via the web portal, and connect your devices. Most Adelaide businesses are operational within an hour using this straightforward process."},
        {"q": "What internet connection do I need for VoIP in Adelaide?", "a": "Any reliable NBN connection is sufficient. Adelaide CBD offices typically have access to fibre-to-the-premises (FTTP) or fibre-to-the-building (FTTB) services, which are ideal for VoIP. Each concurrent call uses around 100kbps, so even a basic NBN 25 plan supports multiple simultaneous calls."},
        {"q": "Can I keep my existing Adelaide phone number?", "a": "Yes, you can keep your existing Adelaide phone number. Click2Call includes number porting, allowing you to transfer your current Adelaide 08, 1300, or 1800 number to their platform seamlessly, with no interruption to your service. This ensures continuity and convenience during the transition."},
        {"q": "Is there a contract or minimum term?", "a": "Click2Call does not require a contract or minimum term. We operate on a prepaid billing system with no hidden fees. You load credit onto your account, and your flat-rate monthly fees are deducted from this balance. You can cancel at any time without any cancellation fees or notice periods."},
        {"q": "How much does a VoIP phone system cost for an Adelaide business?", "a": "A VoIP phone system for an Adelaide business includes an Adelaide 08 number for just $10.00 per month (ex GST). Plans start from $25.00 per user per month (ex GST), which includes a local phone number and 300 minutes of outbound calls. There are no setup fees or lock-in contracts."}
    ],
    "Brisbane": [
        {"q": "Can I get a Brisbane 07 phone number with VoIP?", "a": "Yes, Click2Call offers local Brisbane 07 phone numbers that operate over VoIP. You can either obtain a new 07 number or port your existing one seamlessly, ensuring no downtime during the transfer. This service allows you to maintain a local Queensland presence while benefiting from VoIP technology."},
        {"q": "Do I need a technician to set up a VoIP system in Brisbane?", "a": "No, you do not need a technician to set up a VoIP system in Brisbane. Click2Call offers a self-serve setup where you sign up online, select your number, configure settings via the web portal, and connect your devices. Most Brisbane businesses are operational within an hour using this straightforward process."},
        {"q": "What internet connection do I need for VoIP in Brisbane?", "a": "Any reliable NBN connection is sufficient. Brisbane CBD offices typically have access to fibre-to-the-premises (FTTP) or fibre-to-the-building (FTTB) services, which are ideal for VoIP. Each concurrent call uses around 100kbps, so even a basic NBN 25 plan supports multiple simultaneous calls."},
        {"q": "Can I keep my existing Brisbane phone number?", "a": "Yes, you can keep your existing Brisbane phone number. Click2Call includes number porting, allowing you to transfer your current Brisbane 07, 1300, or 1800 number to their platform seamlessly, with no interruption to your service. This ensures continuity and convenience during the transition."},
        {"q": "Is there a contract or minimum term?", "a": "Click2Call does not require a contract or minimum term. We operate on a prepaid billing system with no hidden fees. You load credit onto your account, and your flat-rate monthly fees are deducted from this balance. You can cancel at any time without any cancellation fees or notice periods."},
        {"q": "How much does a VoIP phone system cost for a Brisbane business?", "a": "A VoIP phone system for a Brisbane business includes a Brisbane 07 number for just $10.00 per month (ex GST). Plans start from $25.00 per user per month (ex GST), which includes a local phone number and 300 minutes of outbound calls. There are no setup fees or lock-in contracts."}
    ],
    "Canberra": [
        {"q": "Can I get a Canberra 02 phone number with VoIP?", "a": "Yes, Click2Call offers local Canberra 02 phone numbers that operate over VoIP. You can either obtain a new 02 number or port your existing one seamlessly, ensuring no downtime during the transfer. This service allows you to maintain a local ACT presence while benefiting from VoIP technology."},
        {"q": "Do I need a technician to set up a VoIP system in Canberra?", "a": "No, you do not need a technician to set up a VoIP system in Canberra. Click2Call offers a self-serve setup where you sign up online, select your number, configure settings via the web portal, and connect your devices. Most Canberra businesses are operational within an hour using this straightforward process."},
        {"q": "What internet connection do I need for VoIP in Canberra?", "a": "Any reliable NBN connection is sufficient. Canberra CBD offices typically have access to fibre-to-the-premises (FTTP) or fibre-to-the-building (FTTB) services, which are ideal for VoIP. Each concurrent call uses around 100kbps, so even a basic NBN 25 plan supports multiple simultaneous calls."},
        {"q": "Can I keep my existing Canberra phone number?", "a": "Yes, you can keep your existing Canberra phone number. Click2Call includes number porting, allowing you to transfer your current Canberra 02, 1300, or 1800 number to their platform seamlessly, with no interruption to your service. This ensures continuity and convenience during the transition."},
        {"q": "Is there a contract or minimum term?", "a": "Click2Call does not require a contract or minimum term. We operate on a prepaid billing system with no hidden fees. You load credit onto your account, and your flat-rate monthly fees are deducted from this balance. You can cancel at any time without any cancellation fees or notice periods."},
        {"q": "How much does a VoIP phone system cost for a Canberra business?", "a": "A VoIP phone system for a Canberra business includes a Canberra 02 number for just $10.00 per month (ex GST). Plans start from $25.00 per user per month (ex GST), which includes a local phone number and 300 minutes of outbound calls. There are no setup fees or lock-in contracts."}
    ],
    "Darwin": [
        {"q": "Can I get a Darwin 08 phone number with VoIP?", "a": "Yes, Click2Call offers local Darwin 08 phone numbers that operate over VoIP. You can either obtain a new 08 number or port your existing one seamlessly, ensuring no downtime during the transfer. This service allows you to maintain a local Northern Territory presence while benefiting from VoIP technology."},
        {"q": "Do I need a technician to set up a VoIP system in Darwin?", "a": "No, you do not need a technician to set up a VoIP system in Darwin. Click2Call offers a self-serve setup where you sign up online, select your number, configure settings via the web portal, and connect your devices. Most Darwin businesses are operational within an hour using this straightforward process."},
        {"q": "What internet connection do I need for VoIP in Darwin?", "a": "Any reliable NBN connection is sufficient. Darwin CBD offices typically have access to fibre-to-the-premises (FTTP) or fibre-to-the-building (FTTB) services, which are ideal for VoIP. Each concurrent call uses around 100kbps, so even a basic NBN 25 plan supports multiple simultaneous calls."},
        {"q": "Can I keep my existing Darwin phone number?", "a": "Yes, you can keep your existing Darwin phone number. Click2Call includes number porting, allowing you to transfer your current Darwin 08, 1300, or 1800 number to their platform seamlessly, with no interruption to your service. This ensures continuity and convenience during the transition."},
        {"q": "Is there a contract or minimum term?", "a": "Click2Call does not require a contract or minimum term. We operate on a prepaid billing system with no hidden fees. You load credit onto your account, and your flat-rate monthly fees are deducted from this balance. You can cancel at any time without any cancellation fees or notice periods."},
        {"q": "How much does a VoIP phone system cost for a Darwin business?", "a": "A VoIP phone system for a Darwin business includes a Darwin 08 number for just $10.00 per month (ex GST). Plans start from $25.00 per user per month (ex GST), which includes a local phone number and 300 minutes of outbound calls. There are no setup fees or lock-in contracts."}
    ],
    "Gold Coast": [
        {"q": "Can I get a Gold Coast 07 phone number with VoIP?", "a": "Yes, Click2Call offers local Gold Coast 07 phone numbers that operate over VoIP. You can either obtain a new 07 number or port your existing one seamlessly, ensuring no downtime during the transfer. This service allows you to maintain a local Queensland presence while benefiting from VoIP technology."},
        {"q": "Do I need a technician to set up a VoIP system on the Gold Coast?", "a": "No, you do not need a technician to set up a VoIP system on the Gold Coast. Click2Call offers a self-serve setup where you sign up online, select your number, configure settings via the web portal, and connect your devices. Most Gold Coast businesses are operational within an hour using this straightforward process."},
        {"q": "What internet connection do I need for VoIP on the Gold Coast?", "a": "Any reliable NBN connection is sufficient. Gold Coast offices typically have access to fibre-to-the-premises (FTTP) or fibre-to-the-building (FTTB) services, which are ideal for VoIP. Each concurrent call uses around 100kbps, so even a basic NBN 25 plan supports multiple simultaneous calls."},
        {"q": "Can I keep my existing Gold Coast phone number?", "a": "Yes, you can keep your existing Gold Coast phone number. Click2Call includes number porting, allowing you to transfer your current Gold Coast 07, 1300, or 1800 number to their platform seamlessly, with no interruption to your service. This ensures continuity and convenience during the transition."},
        {"q": "Is there a contract or minimum term?", "a": "Click2Call does not require a contract or minimum term. We operate on a prepaid billing system with no hidden fees. You load credit onto your account, and your flat-rate monthly fees are deducted from this balance. You can cancel at any time without any cancellation fees or notice periods."},
        {"q": "How much does a VoIP phone system cost for a Gold Coast business?", "a": "A VoIP phone system for a Gold Coast business includes a Gold Coast 07 number for just $10.00 per month (ex GST). Plans start from $25.00 per user per month (ex GST), which includes a local phone number and 300 minutes of outbound calls. There are no setup fees or lock-in contracts."}
    ],
    "Hobart": [
        {"q": "Can I get a Hobart 03 phone number with VoIP?", "a": "Yes, Click2Call offers local Hobart 03 phone numbers that operate over VoIP. You can either obtain a new 03 number or port your existing one seamlessly, ensuring no downtime during the transfer. This service allows you to maintain a local Tasmanian presence while benefiting from VoIP technology."},
        {"q": "Do I need a technician to set up a VoIP system in Hobart?", "a": "No, you do not need a technician to set up a VoIP system in Hobart. Click2Call offers a self-serve setup where you sign up online, select your number, configure settings via the web portal, and connect your devices. Most Hobart businesses are operational within an hour using this straightforward process."},
        {"q": "What internet connection do I need for VoIP in Hobart?", "a": "Any reliable NBN connection is sufficient. Hobart CBD offices typically have access to fibre-to-the-premises (FTTP) or fibre-to-the-building (FTTB) services, which are ideal for VoIP. Each concurrent call uses around 100kbps, so even a basic NBN 25 plan supports multiple simultaneous calls."},
        {"q": "Can I keep my existing Hobart phone number?", "a": "Yes, you can keep your existing Hobart phone number. Click2Call includes number porting, allowing you to transfer your current Hobart 03, 1300, or 1800 number to their platform seamlessly, with no interruption to your service. This ensures continuity and convenience during the transition."},
        {"q": "Is there a contract or minimum term?", "a": "Click2Call does not require a contract or minimum term. We operate on a prepaid billing system with no hidden fees. You load credit onto your account, and your flat-rate monthly fees are deducted from this balance. You can cancel at any time without any cancellation fees or notice periods."},
        {"q": "How much does a VoIP phone system cost for a Hobart business?", "a": "A VoIP phone system for a Hobart business includes a Hobart 03 number for just $10.00 per month (ex GST). Plans start from $25.00 per user per month (ex GST), which includes a local phone number and 300 minutes of outbound calls. There are no setup fees or lock-in contracts."}
    ],
    "Melbourne": [
        {"q": "Can I get a Melbourne 03 phone number with VoIP?", "a": "Yes, Click2Call offers local Melbourne 03 phone numbers that operate over VoIP. You can either obtain a new 03 number or port your existing one seamlessly, ensuring no downtime during the transfer. This service allows you to maintain a local Victorian presence while benefiting from VoIP technology."},
        {"q": "Do I need a technician to set up a VoIP system in Melbourne?", "a": "No, you do not need a technician to set up a VoIP system in Melbourne. Click2Call offers a self-serve setup where you sign up online, select your number, configure settings via the web portal, and connect your devices. Most Melbourne businesses are operational within an hour using this straightforward process."},
        {"q": "What internet connection do I need for VoIP in Melbourne?", "a": "Any reliable NBN connection is sufficient. Melbourne CBD offices typically have access to fibre-to-the-premises (FTTP) or fibre-to-the-building (FTTB) services, which are ideal for VoIP. Each concurrent call uses around 100kbps, so even a basic NBN 25 plan supports multiple simultaneous calls."},
        {"q": "Can I keep my existing Melbourne phone number?", "a": "Yes, you can keep your existing Melbourne phone number. Click2Call includes number porting, allowing you to transfer your current Melbourne 03, 1300, or 1800 number to their platform seamlessly, with no interruption to your service. This ensures continuity and convenience during the transition."},
        {"q": "Is there a contract or minimum term?", "a": "Click2Call does not require a contract or minimum term. We operate on a prepaid billing system with no hidden fees. You load credit onto your account, and your flat-rate monthly fees are deducted from this balance. You can cancel at any time without any cancellation fees or notice periods."},
        {"q": "How much does a VoIP phone system cost for a Melbourne business?", "a": "A VoIP phone system for a Melbourne business includes a Melbourne 03 number for just $10.00 per month (ex GST). Plans start from $25.00 per user per month (ex GST), which includes a local phone number and 300 minutes of outbound calls. There are no setup fees or lock-in contracts."}
    ],
    "Newcastle": [
        {"q": "Can I get a Newcastle 02 phone number with VoIP?", "a": "Yes, Click2Call offers local Newcastle 02 phone numbers that operate over VoIP. You can either obtain a new 02 number or port your existing one seamlessly, ensuring no downtime during the transfer. This service allows you to maintain a local Hunter Region presence while benefiting from VoIP technology."},
        {"q": "Do I need a technician to set up a VoIP system in Newcastle?", "a": "No, you do not need a technician to set up a VoIP system in Newcastle. Click2Call offers a self-serve setup where you sign up online, select your number, configure settings via the web portal, and connect your devices. Most Newcastle businesses are operational within an hour using this straightforward process."},
        {"q": "What internet connection do I need for VoIP in Newcastle?", "a": "Any reliable NBN connection is sufficient. Newcastle CBD offices typically have access to fibre-to-the-premises (FTTP) or fibre-to-the-building (FTTB) services, which are ideal for VoIP. Each concurrent call uses around 100kbps, so even a basic NBN 25 plan supports multiple simultaneous calls."},
        {"q": "Can I keep my existing Newcastle phone number?", "a": "Yes, you can keep your existing Newcastle phone number. Click2Call includes number porting, allowing you to transfer your current Newcastle 02, 1300, or 1800 number to their platform seamlessly, with no interruption to your service. This ensures continuity and convenience during the transition."},
        {"q": "Is there a contract or minimum term?", "a": "Click2Call does not require a contract or minimum term. We operate on a prepaid billing system with no hidden fees. You load credit onto your account, and your flat-rate monthly fees are deducted from this balance. You can cancel at any time without any cancellation fees or notice periods."},
        {"q": "How much does a VoIP phone system cost for a Newcastle business?", "a": "A VoIP phone system for a Newcastle business includes a Newcastle 02 number for just $10.00 per month (ex GST). Plans start from $25.00 per user per month (ex GST), which includes a local phone number and 300 minutes of outbound calls. There are no setup fees or lock-in contracts."}
    ],
    "Perth": [
        {"q": "Can I get a Perth 08 phone number with VoIP?", "a": "Yes, Click2Call offers local Perth 08 phone numbers that operate over VoIP. You can either obtain a new 08 number or port your existing one seamlessly, ensuring no downtime during the transfer. This service allows you to maintain a local Western Australian presence while benefiting from VoIP technology."},
        {"q": "Do I need a technician to set up a VoIP system in Perth?", "a": "No, you do not need a technician to set up a VoIP system in Perth. Click2Call offers a self-serve setup where you sign up online, select your number, configure settings via the web portal, and connect your devices. Most Perth businesses are operational within an hour using this straightforward process."},
        {"q": "What internet connection do I need for VoIP in Perth?", "a": "Any reliable NBN connection is sufficient. Perth CBD offices typically have access to fibre-to-the-premises (FTTP) or fibre-to-the-building (FTTB) services, which are ideal for VoIP. Each concurrent call uses around 100kbps, so even a basic NBN 25 plan supports multiple simultaneous calls."},
        {"q": "Can I keep my existing Perth phone number?", "a": "Yes, you can keep your existing Perth phone number. Click2Call includes number porting, allowing you to transfer your current Perth 08, 1300, or 1800 number to their platform seamlessly, with no interruption to your service. This ensures continuity and convenience during the transition."},
        {"q": "Is there a contract or minimum term?", "a": "Click2Call does not require a contract or minimum term. We operate on a prepaid billing system with no hidden fees. You load credit onto your account, and your flat-rate monthly fees are deducted from this balance. You can cancel at any time without any cancellation fees or notice periods."},
        {"q": "How much does a VoIP phone system cost for a Perth business?", "a": "A VoIP phone system for a Perth business includes a Perth 08 number for just $10.00 per month (ex GST). Plans start from $25.00 per user per month (ex GST), which includes a local phone number and 300 minutes of outbound calls. There are no setup fees or lock-in contracts."}
    ],
    "Sunshine Coast": [
        {"q": "Can I get a Sunshine Coast 07 phone number with VoIP?", "a": "Yes, Click2Call offers local Sunshine Coast 07 phone numbers that operate over VoIP. You can either obtain a new 07 number or port your existing one seamlessly, ensuring no downtime during the transfer. This service allows you to maintain a local Queensland presence while benefiting from VoIP technology."},
        {"q": "Do I need a technician to set up a VoIP system on the Sunshine Coast?", "a": "No, you do not need a technician to set up a VoIP system on the Sunshine Coast. Click2Call offers a self-serve setup where you sign up online, select your number, configure settings via the web portal, and connect your devices. Most Sunshine Coast businesses are operational within an hour using this straightforward process."},
        {"q": "What internet connection do I need for VoIP on the Sunshine Coast?", "a": "Any reliable NBN connection is sufficient. Sunshine Coast offices typically have access to fibre-to-the-premises (FTTP) or fibre-to-the-building (FTTB) services, which are ideal for VoIP. Each concurrent call uses around 100kbps, so even a basic NBN 25 plan supports multiple simultaneous calls."},
        {"q": "Can I keep my existing Sunshine Coast phone number?", "a": "Yes, you can keep your existing Sunshine Coast phone number. Click2Call includes number porting, allowing you to transfer your current Sunshine Coast 07, 1300, or 1800 number to their platform seamlessly, with no interruption to your service. This ensures continuity and convenience during the transition."},
        {"q": "Is there a contract or minimum term?", "a": "Click2Call does not require a contract or minimum term. We operate on a prepaid billing system with no hidden fees. You load credit onto your account, and your flat-rate monthly fees are deducted from this balance. You can cancel at any time without any cancellation fees or notice periods."},
        {"q": "How much does a VoIP phone system cost for a Sunshine Coast business?", "a": "A VoIP phone system for a Sunshine Coast business includes a Sunshine Coast 07 number for just $10.00 per month (ex GST). Plans start from $25.00 per user per month (ex GST), which includes a local phone number and 300 minutes of outbound calls. There are no setup fees or lock-in contracts."}
    ],
    "Sydney": [
        {"q": "Can I get a Sydney 02 phone number with VoIP?", "a": "Yes, Click2Call offers local Sydney 02 phone numbers that operate over VoIP. You can either obtain a new 02 number or port your existing one seamlessly, ensuring no downtime during the transfer. This service allows you to maintain a local NSW presence while benefiting from VoIP technology."},
        {"q": "Do I need a technician to set up a VoIP system in Sydney?", "a": "No, you do not need a technician to set up a VoIP system in Sydney. Click2Call offers a self-serve setup where you sign up online, select your number, configure settings via the web portal, and connect your devices. Most Sydney businesses are operational within an hour using this straightforward process."},
        {"q": "What internet connection do I need for VoIP in Sydney?", "a": "Any reliable NBN connection is sufficient. Sydney CBD offices typically have access to fibre-to-the-premises (FTTP) or fibre-to-the-building (FTTB) services, which are ideal for VoIP. Each concurrent call uses around 100kbps, so even a basic NBN 25 plan supports multiple simultaneous calls."},
        {"q": "Can I keep my existing Sydney phone number?", "a": "Yes, you can keep your existing Sydney phone number. Click2Call includes number porting, allowing you to transfer your current Sydney 02, 1300, or 1800 number to their platform seamlessly, with no interruption to your service. This ensures continuity and convenience during the transition."},
        {"q": "Is there a contract or minimum term?", "a": "Click2Call does not require a contract or minimum term. We operate on a prepaid billing system with no hidden fees. You load credit onto your account, and your flat-rate monthly fees are deducted from this balance. You can cancel at any time without any cancellation fees or notice periods."},
        {"q": "How much does a VoIP phone system cost for a Sydney business?", "a": "A VoIP phone system for a Sydney business includes a Sydney 02 number for just $10.00 per month (ex GST). Plans start from $25.00 per user per month (ex GST), which includes a local phone number and 300 minutes of outbound calls. There are no setup fees or lock-in contracts."}
    ],
    "Wollongong": [
        {"q": "Can I get a Wollongong 02 phone number with VoIP?", "a": "Yes, Click2Call offers local Wollongong 02 phone numbers that operate over VoIP. You can either obtain a new 02 number or port your existing one seamlessly, ensuring no downtime during the transfer. This service allows you to maintain a local Illawarra presence while benefiting from VoIP technology."},
        {"q": "Do I need a technician to set up a VoIP system in Wollongong?", "a": "No, you do not need a technician to set up a VoIP system in Wollongong. Click2Call offers a self-serve setup where you sign up online, select your number, configure settings via the web portal, and connect your devices. Most Wollongong businesses are operational within an hour using this straightforward process."},
        {"q": "What internet connection do I need for VoIP in Wollongong?", "a": "Any reliable NBN connection is sufficient. Wollongong CBD offices typically have access to fibre-to-the-premises (FTTP) or fibre-to-the-building (FTTB) services, which are ideal for VoIP. Each concurrent call uses around 100kbps, so even a basic NBN 25 plan supports multiple simultaneous calls."},
        {"q": "Can I keep my existing Wollongong phone number?", "a": "Yes, you can keep your existing Wollongong phone number. Click2Call includes number porting, allowing you to transfer your current Wollongong 02, 1300, or 1800 number to their platform seamlessly, with no interruption to your service. This ensures continuity and convenience during the transition."},
        {"q": "Is there a contract or minimum term?", "a": "Click2Call does not require a contract or minimum term. We operate on a prepaid billing system with no hidden fees. You load credit onto your account, and your flat-rate monthly fees are deducted from this balance. You can cancel at any time without any cancellation fees or notice periods."},
        {"q": "How much does a VoIP phone system cost for a Wollongong business?", "a": "A VoIP phone system for a Wollongong business includes a Wollongong 02 number for just $10.00 per month (ex GST). Plans start from $25.00 per user per month (ex GST), which includes a local phone number and 300 minutes of outbound calls. There are no setup fees or lock-in contracts."}
    ]
}

with open('faq_data.json', 'w') as f:
    json.dump(faq_data, f, indent=4)

print("FAQ data generated.")
