/** @type {import('tailwindcss').Config} */
module.exports = {
  // Scan all HTML files in the site for Tailwind class usage.
  // Excludes node_modules, .npm-cache, and the email-signature template.
  content: [
    "*.html",
    // Recursive rather than an explicit directory list. The old list was
    // missing call-centre, number-porting and voip-gold-coast, so classes
    // used only on those pages were purged from the build.
    "**/*.html",
    "!node_modules/**",
  ],
  theme: {
    extend: {
      colors: {
        // Canonical brand palette. Matches assets/css/brand.css so the
        // 'brand-green-*' / 'brand-charcoal' utility classes resolve to
        // the same values whether generated by Tailwind or by brand.css.
        brand: {
          green: {
            DEFAULT: "#3B9C49",
            dark:    "#3B9C49",  // alias for backward compat (see brand.css comment)
            light:   "#4DB860",
            hover:   "#2E7A3A",  // canonical hover-darker
          },
          charcoal: "#111827",
          gray: {
            50:  "#F9FAFB",
            100: "#F3F4F6",
            200: "#E5E7EB",
          },
        },
      },
    },
  },
  plugins: [
    require("@tailwindcss/typography"),
    require("@tailwindcss/aspect-ratio"),
  ],
};
